# Generated by Django 4.2.1 on 2023-06-04 15:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("team", "0003_team_plan"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="plan",
            name="max_client",
        ),
        migrations.RemoveField(
            model_name="plan",
            name="max_leads",
        ),
        migrations.RemoveField(
            model_name="team",
            name="plan",
        ),
        migrations.AlterField(
            model_name="team",
            name="name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
